### ISSUE TITLE
Instruction for Mac

### ISSUE THREAD

**Issue by rabenhorst** [bepursuant/SublimeNodeMCU#2]
I made it run on OS X. Should I prepare a pull request? 

I had to change the _sublime-build_ file

```
{
    "shell_cmd": "\"python\" -u \"$packages/User/SublimeNodeMCU/SublimeNodeMCU.py\" \"$file\"",
    "file_regex": "^(.*\\.lua):([0-9]*):",
    "syntax": "Packages/Lua/Lua.tmLanguage",
}

```

**Comment by bepursuant** [comment]
Thanks @mactr0n, absolutely please submit a pull request and I'll merge it in. It looks like it should work on Windows as long as python is in the PATH.
